name: Deploy

on:
  workflow_call:
    inputs:
      docs_site_repo:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_JSON: deployment.json
    outputs:
      deploy_url: ${{ steps.read_deploy_url.outputs.prop }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.docs_site_repo }}_public
          path: ${{ inputs.docs_site_repo }}/public

      - name: Deploy
        working-directory: ${{ inputs.docs_site_repo }}
        run: |
          echo Deploy preview site - stub
