name: Publish

on:
  workflow_call:
    inputs:
      canary:
        required: false
        type: boolean
        default: false
      package_scope:
        required: true
        type: string
      registry_url:
        required: true
        type: string
    secrets:
      agora_email:
        required: true
      agora_token:
        required: true

jobs:
  publish_job:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Configure npm
        run: |
          npm config set ${{ inputs.package_scope }}:registry ${{ inputs.registry_url }}
          npm config set email ${{ secrets.agora_email }}
          npm config set _auth ${{ secrets.agora_token }}
          npm config set always-auth true

      - name: Create canary package
        if: ${{ inputs.canary == true }}
        run: node .github/scripts/canary-version
        
      - name: Publish canary
        if: ${{ inputs.canary == true }}
        run: npm publish --tag=next

      - name: Publish
        if: ${{ inputs.canary == false }}
        run: npm publish
