name: Publish

on:
  workflow_call:
    inputs:
      canary:
        required: false
        type: boolean
        default: false
      package_scope:
        required: false
        type: string
        default: '@deque'
      registry_url:
        required: true
        type: string
    secrets:
      agora_email:
        required: true
      agora_token:
        required: true

jobs:
  publish_job:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install jq

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Configure npm
        run: |
          npm config set ${{ inputs.package_scope }}:registry ${{ inputs.registry_url }}
          npm config set email ${{ secrets.agora_email }}
          npm config set _auth ${{ secrets.agora_token }}
          npm config set always-auth true

      - name: Update package version
        run: |
          version=`jq -r .version package.json`
          if [ ${{ inputs.canary }} = true ]
          then
            new_version=${GITHUB_SHA:0:8}
            new_manifest=`sed "s/$version/$version-$new_version/g" package.json`
          else
            tag=${GITHUB_REF/refs\/tags\//}
            new_version=${tag/v/}
            new_manifest=`sed "s/$version/$new_version/g" package.json`
          fi
          echo $new_manifest > package.json

      - name: Publish
        run: |
          if [ ${{ inputs.canary }} = true ]
          then
            npm publish --tag=next
          else
            npm publish
          fi
